### ISSUE TITLE
CSRF token mismatch ?

### ISSUE THREAD

**Issue by Ensaia** [gdarko/laravel-vue-starter#10]
getting error while attempt to register ?
![csrf](https://user-images.githubusercontent.com/19869364/233796788-d9b02c02-18b9-43d3-8454-3d3b8cafb26f.png)

**Comment by gdarko** [comment]
Hey @Ensaia90 ,

Please check [this issue](https://github.com/gdarko/laravel-vue-starter/issues/9), it should solve the issue.

Best Regards,
Darko

**Comment by Ensaia** [comment]
i already configure .env file as you mention
