### ISSUE TITLE
HMR hot module replacement fix

### ISSUE THREAD

**Issue by CarstenRuetz** [gdarko/laravel-vue-starter#8]
Hi @gdarko 

first of all: nice work! I am just building my own template stack and really appreciated yours :)

Noticed and fixed one thing: 

`npm run dev 
`starts the hot module replacement mode but always gave an error in the browser console: 

`client.ts:113 ReferenceError: Cannot access 'routes' before initialization`

Seems this is related to circular dependencies: https://github.com/vitejs/vite/issues/3033

In your case, changing to lazy loaded components in the routes.js fixed this issue: 
```
    {
        name: "home",
        path: "/",
        meta: { requiresAuth: false },
        // component: PageLogin,
        component: () => import("@/views/pages/auth/login/Main"),
    },
```

Cheers!

**Comment by gdarko** [comment]
After upgrading the Vue version, the issue seems to be gone.

closing now.
