### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by sayedahmadnawid** [gdarko/laravel-vue-starter#9]
I have been trying to figure out this issue, I couldn't really fix this. I thing there is issue with CORS. Though I traced, everything regarding the CORS is ok. 

Could anyone please help me?

<img width="1315" alt="Screen Shot 2023-02-11 at 18 17 02" src="https://user-images.githubusercontent.com/12025673/218250546-65d54fc3-9a11-49ac-af61-d87267a13b21.png">

**Comment by gdarko** [comment]
Hey @sayedahmadnawid ,

Can you please check in your [.env](https://github.com/gdarko/laravel-vue-starter/blob/master/.env.example) file, your domains should be the same. Something like this:

```
APP_URL=http://localhost:8000

SANCTUM_STATEFUL_DOMAINS=localhost:8000
SESSION_DOMAIN=localhost
```

Let me know if that helps.

Best,
Darko

**Comment by sayedahmadnawid** [comment]
@gdarko 

Thank you very much. Exactly, this solution helped me.
